### PR TITLE
PR feature/14--hello-lodash

### PR DESCRIPTION
**Pull request by mfees**
https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/168

### CODE REVIEW

**Comment by eklemen** [comment]
:+1:  awesome

**Comment by KolbySisk** [comment]
:+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1:

**Comment by mfees** [comment]
<3 ^

**Comment by carolinapowers** [comment]
:+1:

**Pull request merged**
